---
title: "Testing new functions"
author: "Clara Bicalho"
date: "2025-07-04"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, message=FALSE, warning=FALSE}
library(pwtest)
library(tidymodels)
source("~/Library/CloudStorage/Dropbox/Github-Cloud/prognostic_balance/code/simulations/R/simulate_experiment_poly_4.R")
data <- simulate_experiment(N = 1000, imbalance = rep(.2, 3), prognosis = c(.3, .2, .1), poly = c(2, 1))
```

# pwtest() with `cv_auto = FALSE` (default) option

```{r}
pwtest(data, 
       model_spec = rand_forest(mode = "regression"),
       covariates = c("X1", "X2", "X1_2"),
       n_bootstraps = 200)
```

# test function `contest()`

```{r}
data_control <- data[data$Z == 0, c("X1", "X2", "X1_2", "Y")]
contest(data_control, 
        covariates = c("X1", "X2", "X1_2", "Y"), 
        outcome = "Y", 
        verbose = TRUE) 

# takes defaults values for
# cv_folds = 5
# min_penalty_exp = -6
# max_penalty_exp = -1
```

# test function `pick_winner()` (previously `prognostic_balance()`)

```{r}
pick_winner(data_control, 
            covariates = c("X1", "X2", "X1_2", "Y"), 
            outcome = "Y", 
            verbose = TRUE) 
# takes defaults values for
# cv_folds = 3
# min_penalty_exp = -6
# max_penalty_exp = -1
```

# pwtest() with `cv_auto = TRUE` option (nests `pick_winner` and `contest`)

```{r}
pwtest(data, 
       model_spec = NULL,
       covariates = c("X1", "X2", "X1_2"),
       n_bootstraps = 200,
       cv_auto = TRUE, verbose = TRUE, min_penalty_exp = 0)
```
